# Generated by Django 6.1 on 2026-09-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short summary of what this form is used for.')),
                ('icon_name', models.CharField(default='description', help_text="Use Google Material Symbol names (e.g., 'description', 'health_and_safety', 'assignment')", max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='official_forms/')),
                ('pages', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='agmreport',
            name='description',
            field=models.TextField(default='Official audited financials and executive committee reports for the fiscal year.', help_text='Summary of the report.'),
        ),
        migrations.AddField(
            model_name='agmreport',
            name='icon_name',
            field=models.CharField(default='pie_chart', help_text="Use Google Material Symbol names (e.g., 'pie_chart', 'analytics')", max_length=50),
        ),
        migrations.AlterField(
            model_name='agmreport',
            name='document',
            field=models.FileField(upload_to='agm_reports/'),
        ),
        migrations.AlterField(
            model_name='agmreport',
            name='title',
            field=models.CharField(default='AGM Report', max_length=200),
        ),
        migrations.AlterField(
            model_name='agmreport',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agmreport',
            name='year',
            field=models.IntegerField(),
        ),
    ]
