# Generated by Django 6.1 on 2026-09-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_downloadableform_agmreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmreport',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
