# Generated by Django 6.1 on 2026-09-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_agmreport_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableform',
            name='document',
            field=models.FileField(default='', upload_to='official_forms/'),
            preserve_default=False,
        ),
    ]
