# Generated by Django 6.1 on 2026-09-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_newslettersubscriber_portalwaitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='PortalWaitlist',
        ),
    ]
