# Generated by Django 6.1 on 2026-09-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_delete_newslettersubscriber_delete_portalwaitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AGMReport',
        ),
        migrations.DeleteModel(
            name='DownloadableForm',
        ),
    ]
