# Generated by Django 6.1 on 2026-09-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('happening', 'Recent Happening (Short)'), ('blog', 'Blog Post (Long-form)')], default='blog', max_length=20)),
                ('summary', models.TextField(help_text='Short description for the homepage cards.')),
                ('content', models.TextField(help_text='The full article text with formatting, images, and links.')),
                ('cover_image', models.ImageField(upload_to='news_images/')),
                ('author', models.CharField(default='Finance Committee', max_length=100)),
                ('published_date', models.DateField()),
                ('tag', models.CharField(blank=True, help_text='e.g., Dividends, Import Guide', max_length=50)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
