# Generated by Django 6.1 on 2026-09-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='tag',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_blog_post',
            field=models.BooleanField(default=True, help_text="Check this to display in the bottom 'Cooperative Insights' blog grid."),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_recent_happening',
            field=models.BooleanField(default=False, help_text="Check this to feature in the top 3 'Recent Happenings' grid."),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='topic',
            field=models.CharField(choices=[('dividends', 'Dividends & Shares'), ('loans', 'Loans & Credit'), ('security', 'Digital Safety & Security'), ('governance', 'Governance & Leadership'), ('health', 'Healthcare & Practice')], default='dividends', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(help_text='Full article body (uses Summernote editor).'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(help_text='Short excerpt for homepage preview cards.'),
        ),
    ]
