# Generated by Django 6.1 on 2026-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_newsarticle_category_remove_newsarticle_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin to the giant top Hero section. (Checking this automatically unpins the previous one).'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='is_recent_happening',
            field=models.BooleanField(default=False, help_text="Check this to feature in the top 3 'Recent Happenings' grid on the home page."),
        ),
    ]
