# Generated by Django 6.1 on 2026-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_newsarticle_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Drafts are hidden from the public site.', max_length=10),
        ),
    ]
