# Generated by Django 6.1 on 2026-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='action_url',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text='Use HTML for inline links. Example: Join tomorrow\'s AGM <a href="https://zoom.us/...">via this link</a>.'),
        ),
    ]
