# Generated by Django 6.1 on 2026-09-22 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_newslettersubscriber_portalwaitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('category', models.CharField(choices=[('form', 'Application Form'), ('report', 'Statement & Report'), ('agm', 'AGM Minutes / Report'), ('legal', 'Policy & By-Laws')], default='form', max_length=10)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Required for AGM documents — drives the auto-generated title in the admin form.', null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('icon_name', models.CharField(choices=[('description', 'Document'), ('person_add', 'Person (single applicant)'), ('group_add', 'Group / Guarantor'), ('gavel', 'Governance / Legal'), ('receipt_long', 'Statement / Report'), ('health_and_safety', 'Health / Insurance'), ('badge', 'ID / Membership'), ('account_balance', 'Institutional')], default='description', max_length=40)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=280)),
                ('category', models.CharField(choices=[('agm', 'AGM Meetings'), ('outreach', 'Community Outreach'), ('hospital', 'Hospital Visits')], default='agm', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery/%Y/')),
                ('media_type', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='administrator.galleryalbum')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='PortalWaitlist',
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_blog_post',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_recent_happening',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='topic',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True, help_text='Rich HTML content from the article editor'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('dividend', 'Dividends'), ('guide', 'Financial Literacy'), ('security', 'Security & Portal'), ('news', 'Union Governance')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Shown in the article grid teaser', max_length=160),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/featured/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(help_text="Author or committee name, e.g. 'Finance Committee'", max_length=120),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=220),
        ),
    ]
