# Generated by Django 6.1 on 2026-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_newslettersubscriber_portalwaitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Use HTML for inline links. Example: Join tomorrow\'s AGM <a href="https://zoom.us/...">via this link</a>.')),
                ('alert_type', models.CharField(choices=[('info', 'Information (Blue)'), ('warning', 'Warning/Reminder (Yellow)'), ('urgent', 'Urgent/Critical (Red)')], default='warning', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this announcement globally.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
