# Generated by Django 6.1 on 2026-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text='Keep it brief. Paste URLs normally, or use Markdown for custom link text: [Click Here](https://example.com)'),
        ),
    ]
