# Generated by Django 6.1 on 2026-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Check this to display the announcement site-wide. Uncheck to hide it.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text="Keep it brief. Paste URLs normally (defaults to 'View Link'), or use Markdown for custom text: [Click Here](https://example.com)"),
        ),
    ]
