# Generated by Django 6.1 on 2026-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_document_deleted_at_document_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
