# Generated by Django 6.1 on 2026-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_galleryalbum_deleted_at_galleryalbum_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
