# Generated by Django 6.1 on 2026-09-27 23:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_galleryalbum_status_alter_galleryalbum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
