# Generated by Django 6.1 on 2026-09-28 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_galleryalbum_public_id_gallerymedia_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
