# Generated by Django 6.1 on 2026-09-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_document_public_id_newsarticle_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbum',
            name='category',
            field=models.CharField(choices=[('agm', 'AGM Meetings'), ('outreach', 'Community Outreach'), ('hospital', 'Hospital Visits'), ('promo', 'Promotional & Media')], default='agm', max_length=10),
        ),
    ]
