# Generated by Django 6.1 on 2026-09-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_alter_galleryalbum_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Cached file size in bytes to prevent N+1 Cloudflare queries', null=True),
        ),
    ]
